/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package junit.vintage.parallel;


import org.junit.Test;

public class VintageTest3 {

    @Test
    public void slowTest1() throws InterruptedException {
        SimulateSlow.simulateSlow();
    }

    @Test
    public void slowTest2() throws InterruptedException {
        SimulateSlow.simulateSlow();
    }
}
